[package]
name = "edit"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = {version = "0.26", features = ["event-stream"]}
ratatui = {version = "0.23.0", features = ["all-widgets"]}
ropey = "1.6.1"
edit_core = {path = "../edit_core"}
