[package]
name = "edit"
version = "0.1.0"
edition = "2021"

[dependencies]
unicode-segmentation = "1"
crossterm = {version = "0.26", features = ["event-stream"]}
ratatui = {version = "0.23.0", features = ["all-widgets"]}
ron = "0.8"
ropey = "1.6.1"
